name: Actualizar Pronosticos Diario

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  sincronizar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependencias
        run: pip install requests
        
      - name: Ejecutar script de ESPN
        run: python actualizar_datos.py
        
      - name: Guardar y subir cambios
        run: |
          git config --global user.name "Bot Automatico"
          git config --global user.email "bot@actions.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add -A
          git commit -m "Actualizacion automatica [skip ci]" || echo "Sin cambios"
          git push origin principal
